# Generated by Django 6.0.2 on 2026-07-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_mosaic", "0013_alter_contentimage_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=512)),
                ("cid", models.CharField(max_length=256)),
                ("rkey", models.CharField(max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.CharField(max_length=512)),
                ("cid", models.CharField(max_length=256)),
                ("rkey", models.CharField(max_length=64)),
                (
                    "bsky_post_uri",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "bsky_post_cid",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atproto_document",
                        to="django_mosaic.post",
                    ),
                ),
            ],
        ),
    ]
