# Generated by Django 6.0.2 on 2026-07-03 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mosaic", "0012_alter_post_options_alter_tag_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_mosaic.post",
            ),
        ),
    ]
